---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - prometheusrule.yaml
  - webhook/
configMapGenerator:
  - name: flux-instance-helm-values
    files:
      - values.yaml=helm-values.yaml
  - name: flux-webhook-gatus-ep
    files:
      - config.yaml=webhook/gatus-config.yaml
    options:
      disableNameSuffixHash: true
      labels:
        gatus.io/enabled: "true"
configurations:
  - kustomizeconfig.yaml
