---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmpodscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: node-feature-discovery
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - node-feature-discovery
      - key: app.kubernetes.io/name
        operator: In
        values:
          - node-feature-discovery
  podMetricsEndpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: http
      scheme: http
