---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-ai
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://go-skynet.github.io/helm-charts/
      chart: local-ai
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: go-skynet
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicaCount: 1
    fullnameOverride: "local-ai"

    deployment:
      image:
        repository: quay.io/go-skynet/local-ai
        tag: v2.29.0-aio-gpu-nvidia-cuda-12
      env:
        threads: 8
        context_size: 512
      modelsPath: "/models"

    resources:
      requests:
        cpu: 200m
        memory: 1Gi
        nvidia.com/gpu: 1
      limits:
        memory: 24Gi
        nvidia.com/gpu: 1

    persistence:
      models:
        enabled: true
        storageClass: "openebs-hostpath" # Use default storage class
        accessModes:
          - ReadWriteOnce
        size: 100Gi
        globalMount: /models
      output:
        enabled: false
        globalMount: /tmp/generated

    service:
      annotations:
        io.cilium/lb-ipam-ips: 192.168.20.40
        external-dns.alpha.kubernetes.io/hostname: localai.internal
      type: LoadBalancer
      ports:
        http:
          port: 8080

    ingress:
      enabled: true
      className: tailscale
      annotations: {}
      hosts:
        - host: &host localai.kite-harmonic.ts.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
