---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: &cluster hindwing
spec:
  # renovate: datasource=docker depName=ghcr.io/dragonflydb/dragonfly
  image: ghcr.io/dragonflydb/dragonfly:v1.37.0
  replicas: 3
  args:
    - --maxmemory=$(MAX_MEMORY)Mi
    - --proactor_threads=2
    - --cluster_mode=emulated
    - --lock_on_hashtags
    - --s3_endpoint=https://s3.us-west-001.backblazeb2.com
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: hindwing-s3-secret
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: hindwing-s3-secret
          key: AWS_SECRET_ACCESS_KEY
  snapshot:
    cron: "15 */4 * * *"
    dir: s3://cluster-db-backup/hindwing
    enableOnMasterOnly: true
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 512Mi
  serviceSpec:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: redis.internal
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: *cluster
