---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hindwing-s3
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hindwing-s3-secret
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: barman-b2-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: barman-b2-credentials
        property: AWS_SECRET_ACCESS_KEY
