---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmpodscrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: hindwing
spec:
  selector:
    matchLabels:
      app: hindwing
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: admin
