---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cross-seed-secret
    template:
      engineVersion: v2
      data:
        CROSS_SEED_API_KEY: "{{ .CROSS_SEED_API_KEY }}"
        PROWLARR_API_KEY: "{{ .PROWLARR_API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
        RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: prowlarr
