---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: cross-seed-configmap
    files:
      - resources/config-daemon.js
      - resources/config-search.js
generatorOptions:
  disableNameSuffixHash: true
