---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: steam-headless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: steam-headless-secret
    template:
      engineVersion: v2
      data:
        USER_PASSWORD: "{{ .STEAM_HEADLESS_PASSWORD }}"
        SUNSHINE_USER: "{{ .SUNSHINE_USERNAME }}"
        SUNSHINE_PASS: "{{ .SUNSHINE_PASSWORD }}"

  dataFrom:
    - extract:
        key: steam-headless
    - extract:
        key: sunshine
