---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: steam-library
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1.5Ti
  storageClassName: openebs-hostpath
