---
apiVersion: v1
kind: Service
metadata:
  name: redspot-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redspot.zebernst.dev
    io.cilium/lb-ipam-ips: 10.2.100.16
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: redspot16
    cnpg.io/instanceRole: primary
