# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/database_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: grafana
spec:
  cluster:
    name: redspot
  name: grafana
  owner: grafana
  ensure: present
  databaseReclaimPolicy: retain
