# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/databaserole_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: grafana
spec:
  cluster:
    name: redspot
  name: grafana
  comment: Grafana application role
  login: true
  # retain leaves the role in Postgres if this resource is deleted
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: grafana-db-role
