# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-db-role
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: grafana
        password: "{{ .POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: grafana
