---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmalertmanagerconfig_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    group_by: ["alertname", "cluster", "job"]
    group_interval: 10m
    group_wait: 1m
    receiver: pushover
    repeat_interval: 12h
    routes:
      - receiver: blackhole
        matchers:
          - alertname="InfoInhibitor"
      - receiver: heartbeat
        group_interval: 5m
        group_wait: 0s
        repeat_interval: 1m
        matchers:
          - alertname="Watchdog"
  inhibit_rules:
    - equal: ["alertname", "namespace"]
      source_matchers:
        - severity="critical"
      target_matchers:
        - severity="warning"
  receivers:
    - name: blackhole
    - name: heartbeat
      webhook_configs:
        - url_secret:
            name: alertmanager-secret
            key: ALERTMANAGER_HEARTBEAT_URL
    - name: pushover
      pushover_configs:
        - html: true
          message: |-
            {{- range .Alerts }}
              {{- if ne .Annotations.description "" }}
                {{ .Annotations.description }}
              {{- else if ne .Annotations.summary "" }}
                {{ .Annotations.summary }}
              {{- else if ne .Annotations.message "" }}
                {{ .Annotations.message }}
              {{- else }}
                Alert description not available
              {{- end }}
              {{- if ne .Annotations.runbook_url "" }}
                <p><a href="{{ .Annotations.runbook_url }}">Runbook</a></p>
              {{- end }}
              {{- if gt (len .Labels.SortedPairs) 0 }}
                <small>
                  {{- range .Labels.SortedPairs }}
                    <b>{{ .Name }}:</b> {{ .Value }}
                  {{- end }}
                </small>
              {{- end }}
            {{- end }}
          priority: |-
            {{- if eq .Status "firing" -}}
              {{- if eq .CommonLabels.severity "critical" -}}1
              {{- else if eq .CommonLabels.severity "warning" -}}-1
              {{- else -}}0
              {{- end -}}
            {{- else -}}
              {{- if eq .CommonLabels.severity "critical" -}}0
              {{- else -}}-2
              {{- end -}}
            {{- end -}}
          send_resolved: true
          sound: gamelan
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
            {{ .CommonLabels.alertname }}
          token:
            name: alertmanager-secret
            key: ALERTMANAGER_PUSHOVER_TOKEN
          user_key:
            name: alertmanager-secret
            key: PUSHOVER_USER_KEY
          url_title: View in Alertmanager
