---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: ics-on-call
  namespace: fission
spec:
  environment:
    name: python
    namespace: fission
  source:
    type: literal
    literal: UEsDBBQACAAIANAanVwAAAAAAAAAAPsCAAAHABwAY29kZS5weVVUCQADd3nxaXd58Wl1eAsAAQQAAAAABAAAAAB9Uc1uozAQvvMUI2sPpgXS7amiykpRk0OltFpt6R420MjFJrFkDLIHqVG3775DICsOTZFAY+b7m3HlmhpagXujX0HXbeMQftIxGGunglO5R2zfgiCQqoJaaMtDiH8Adq1RG48uAm0xAqlLHI70KYo0AHq8Kp3CrdQO5mDVG/Leg7PZ0PCzSnuvG8vCRKNyhONheGSWja307hPm0DjDPFI7Z4jDJ94zYF1LsZSoY+oSh0q5xV42TKihWz7Y0kZIzfb8SQLi+66uhTvEI+ALCadaI0pVK4vnZSagM1KnLeCgc7yEZKeQ0wBh0oPHaW3VGKkkYZxKfPfKHctdbjeQY8EiYPSOMqd8VtRT/DhSNE0e/deNoDJi5+cEfnheZ/fr+8fVICSM2UpxmBq/8GX2lC1+ZX+X2epxGW5e0uIi5bl8v/kIs00u/xSX3ygQRfx++3uxfl7Nl4tslebX/c8h2OeGY3Ts6HJG4wiur64ieGd3w3hxdmgVS4H1y5mVwigrhbuFci+cVzjvsIpv2EfwD1BLBwh49LAtjgEAAPsCAABQSwMEFAAIAAgAjxSdXAAAAAAAAAAAbAAAAA4AHABweXByb2plY3QudG9tbFVUCQADrm7xaa5u8Wl1eAsAAQQAAAAABAAAAAAlyUEOQDAQRuH9nKKZtTYaay4iFlJ/osK02hJuj3jL7/UxhQWuDCTjBtUq9i7rINqN68p0ImUf5PPaWFMzJeyHT8g63mX+T9c2xlqmCREyQZxHfr0n9cZzKfHiigZ6AFBLBwi9OnwkXwAAAGwAAABQSwECHgMUAAgACADQGp1cePSwLY4BAAD7AgAABwAYAAAAAAABAAAApIEAAAAAY29kZS5weVVUBQADd3nxaXV4CwABBAAAAAAEAAAAAFBLAQIeAxQACAAIAI8UnVy9OnwkXwAAAGwAAAAOABgAAAAAAAEAAACkgd8BAABweXByb2plY3QudG9tbFVUBQADrm7xaXV4CwABBAAAAAAEAAAAAFBLBQYAAAAAAgACAKEAAACWAgAAAAA=
