---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: ics-on-call
  namespace: fission
spec:
  environment:
    name: python
    namespace: fission
  source:
    type: literal
    literal: UEsDBBQACAAIAJ0amFwAAAAAAAAAAMsCAAAHABwAY29kZS5weVVUCQADmuHqaZrh6ml1eAsAAQQAAAAABAAAAAB9UUtr4zAQvvtXDNqLzPpRygaWLNlL2EAgLSXbnpoQFHucCGxZSCNoKP3vO35k8aGpQWbEfI/5RpVrG7CKzrU+gm5s6wie+BqNtcPoWp6J7FsURSVW0ChtZAzpb6Bga3z15BLQhhIodUHDlX/7/TwC/jwWDulQagcLMPhGsvOQIh8aPq+097o1Is40oWOcjOOeWbSm0qdPmEPjBrOnBlczR068cxDB8liompS7zOGyPFAnG2fc0FYOtrwRVjMdfzIB831oGuUu6Qj4QsKhrVWBDRq6LTMB3ZC6boEGnf4RshOS5ABx1oEHyDd4MVVbl7Be/oVaG+xJ2gRFvB4Pcrtawmz2YzaH5Xazgu/gLTvnpI7DvKGnY8kmDjMfjtKJnduZV9jRXiQg+IxzXAMa1Uzx406SafTkv24CVa1OfsHgh5fN83qzfvwzxuP3CbzsUTCB+7u7BN7FcnBLny8WxRxEFzYvVI2mVO4XFGflPNIiUJX+FB/RP1BLBwgTcHjNdgEAAMsCAABQSwMEFAAIAAgAihOYXAAAAAAAAAAAbAAAAA4AHABweXByb2plY3QudG9tbFVUCQADQ9XqaUPV6ml1eAsAAQQAAAAABAAAAAAlyUEOQDAQRuH9nKKZtTYaay4iFlJ/osK02hJuj3jL7/UxhQWuDCTjBtUq9i7rINqN68p0ImUf5PPaWFMzJeyHT8g63mX+T9c2xlqmCREyQZxHfr0n9cZzKfHiigZ6AFBLBwi9OnwkXwAAAGwAAABQSwECHgMUAAgACACdGphcE3B4zXYBAADLAgAABwAYAAAAAAABAAAApIEAAAAAY29kZS5weVVUBQADmuHqaXV4CwABBAAAAAAEAAAAAFBLAQIeAxQACAAIAIoTmFy9OnwkXwAAAGwAAAAOABgAAAAAAAEAAACkgccBAABweXByb2plY3QudG9tbFVUBQADQ9XqaXV4CwABBAAAAAAEAAAAAFBLBQYAAAAAAgACAKEAAAB+AgAAAAA=
