---
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: ics-on-call
  namespace: fission
spec:
  relativeurl: /ics/oncall
  method: GET
  functionref:
    type: name
    name: ics-on-call
  ingressconfig:
    annotations: {}
