---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    template:
      engineVersion: v2
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            dataDirs: ["/media/plex/TV Shows/Source", "/media/plex/Movies/Source", "/media/downloads/qbittorrent/"],
            delay: 30,
            duplicateCategories: false,
            flatLinking: false,
            includeNonVideos: false,
            includeSingleEpisodes: false,
            linkCategory: "cross-seed",
            linkDir: "/media/downloads/cross-seed/links",
            linkType: "hardlink",
            matchMode: "partial",
            outputDir: "/media/downloads/cross-seed/output",
            port: 80,
            qbittorrentUrl: "http://qbittorrent.default.svc.cluster.local",
            radarr: ["http://radarr.default.svc.cluster.local/?apikey={{ .RADARR_API_KEY }}"],
            skipRecheck: false,
            sonarr: ["http://sonarr.default.svc.cluster.local/?apikey={{ .SONARR_API_KEY }}"],
            torrentDir: "/qbittorrent/qBittorrent/BT_backup",
            torznab: [
                2,  // PTP
                12, // TL
                16, // GT
                18, // MLK
                19, // JPTV
            ].map(i => `http://prowlarr.default.svc.cluster.local/$${i}/api?apikey={{ .PROWLARR_API_KEY }}`),
          };
  dataFrom:
    - extract:
        key: cross-seed
    - extract:
        key: radarr
    - extract:
        key: sonarr
    - extract:
        key: prowlarr
