# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tinyauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TINYAUTH_APPURL: "https://auth.zebernst.dev"
        TINYAUTH_OAUTH_AUTOREDIRECT: "pocketid"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: "{{ .POCKETID_CLIENTID }}"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: "{{ .POCKETID_CLIENTSECRET }}"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL: "https://id.zebernst.dev/authorize"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL: "https://id.zebernst.dev/api/oidc/token"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL: "https://id.zebernst.dev/api/oidc/userinfo"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL: "https://auth.zebernst.dev/api/oauth/callback/pocketid"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES: "openid email profile groups"
  dataFrom:
    - extract:
        key: tinyauth
