[env]
KUBECONFIG = "{{config_root}}/kubernetes/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
TALOSCONFIG = "{{config_root}}/talos/talosconfig"

# Included file paths
_.file = [
  "{{config_root}}/kubernetes/apps/system-upgrade/versions.env"
]

[tools]
1password-cli = "latest"
age = "latest"
"aqua:cert-manager/cmctl" = "latest"
"aqua:cloudnative-pg/cloudnative-pg/kubectl-cnpg" = "latest"
"aqua:elsesiy/kubectl-view-secret" = "latest"
"aqua:kvaps/kubectl-node-shell" = "latest"
cilium-cli = "latest"
cloudflared = "latest"
flux2 = "latest"
gh = "latest"
helm = "latest"
helm-diff = "latest"
helmfile = "latest"
jq = "latest"
k9s = "latest"
krew = "latest"
kubecolor = "latest"
kubectl = "latest"
kustomize = "latest"
"pipx:allenporter/flux-local" = "latest"
talhelper = "latest"
talosctl = "latest"
task = "latest"
"ubi:clbx/kubectl-browse-pvc" = "latest"
"ubi:mitsuhiko/minijinja" = { version = "latest", exe = "minijinja-cli" }
"ubi:rook/kubectl-rook-ceph" = "latest"
yq = "latest"
