---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  SCRIPTS_DIR: "{{.ROOT_DIR}}/scripts"
  # Files
  AGE_FILE: "{{.ROOT_DIR}}/age.key"
  BOOTSTRAP_CONFIG_FILE: "{{.ROOT_DIR}}/config.yaml"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_CONFIG_FILE: "{{.ROOT_DIR}}/.sops.yaml"

env:
  KUBECONFIG: "{{.KUBECONFIG_FILE}}"
  SOPS_AGE_KEY_FILE: "{{.AGE_FILE}}"

includes:
  kubernetes: .taskfiles/Kubernetes
  flux: .taskfiles/Flux
  repository: .taskfiles/Repository
  talos: .taskfiles/Talos
  sops: .taskfiles/Sops
  user:
    taskfile: .taskfiles/User
    optional: true

tasks:

  default: task --list
