---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: public.ecr.aws/emqx/emqx:5.8.4
  config:
    data: |
      authentication {
        backend = "built_in_database"
        mechanism = "password_based"
        password_hash_algorithm {
            name = "bcrypt"
        }
        user_id_type = "username"
        bootstrap_file = "/opt/init-user.json"
        bootstrap_type = "plain"
      }
      authorization {
        deny_action = ignore
        no_match = allow
        sources = [
          {
            type = file
            enable = true
            path = "/etc/acl.conf"
          }
        ]
      }
  coreTemplate:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      replicas: 3
      envFrom:
        - secretRef:
            name: emqx-secret
      extraVolumeMounts:
        - name: authz
          mountPath: /opt/init-user.json
          subPath: init-user.json
          readOnly: true
        - name: authz
          mountPath: /etc/acl.conf
          subPath: acl.conf
          readOnly: true
      extraVolumes:
        - name: authz
          secret:
            secretName: emqx-authz-secret
  listenersServiceTemplate:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.zebernst.dev
        io.cilium/lb-ipam-ips: 10.2.100.8
    spec:
      type: LoadBalancer
