---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: emqx-authz
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: emqx-authz-secret
    template:
      engineVersion: v2
      data:
        init-user.json: |
          [
            {"user_id": "{{ .EMQX_MQTT_INIT_USERNAME }}", "password": "{{ .EMQX_MQTT_INIT_PASSWORD }}", "is_superuser": true},
            {"user_id": "{{ .HOME_ASSISTANT_MQTT_USERNAME }}", "password": "{{ .HOME_ASSISTANT_MQTT_PASSWORD }}", "is_superuser": false},
            {"user_id": "{{ .ZIGBEE2MQTT_MQTT_USERNAME }}", "password": "{{ .ZIGBEE2MQTT_MQTT_PASSWORD }}", "is_superuser": false}
          ]
        acl.conf: |
          %% Home Assistant
          {allow, {user, "{{ .HOME_ASSISTANT_MQTT_USERNAME }}"}, all, ["homeassistant/#", "+/discover/#", "+/discovery/#"]}.
          {allow, {user, "{{ .HOME_ASSISTANT_MQTT_USERNAME }}"}, all, ["esphome/#"]}.
          {allow, {user, "{{ .HOME_ASSISTANT_MQTT_USERNAME }}"}, all, ["valetudo/#"]}.
          {allow, {user, "{{ .HOME_ASSISTANT_MQTT_USERNAME }}"}, all, ["zigbee2mqtt/#"]}.

          %% Zigbee2MQTT
          {allow, {user, "{{ .ZIGBEE2MQTT_MQTT_USERNAME }}"}, all, ["zigbee2mqtt/#"]}.
          {allow, {user, "{{ .ZIGBEE2MQTT_MQTT_USERNAME }}"}, publish, ["homeassistant/+/+/config"]}.
          {allow, {user, "{{ .ZIGBEE2MQTT_MQTT_USERNAME }}"}, publish, ["homeassistant/+/+/+/config"]}.
          {allow, {user, "{{ .ZIGBEE2MQTT_MQTT_USERNAME }}"}, subscribe, ["homeassistant/status"]}.
          {allow, {user, "{{ .ZIGBEE2MQTT_MQTT_USERNAME }}"}, subscribe, ["homeassistant/#"]}.

          %% Default
          {deny, all}.

  dataFrom:
    - extract:
        key: emqx
