---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx
  annotations:
    hajimari.io/instance: tailscale
    hajimari.io/icon: simple-icons:mqtt
spec:
  ingressClassName: tailscale
  rules:
    - host: &host emqx.kite-harmonic.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emqx-dashboard
                port:
                  number: 18083
  tls:
    - hosts:
        - *host
