---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaAlertRuleGroup
metadata:
  name: autobrr
spec:
  allowCrossNamespaceImport: true
  folderRef: default
  instanceSelector:
    matchLabels:
      dashboards: "grafana-cloud"
  interval: 1m
  rules:
    - uid: bec817a1-5d94-44aa-8103-13ed5a1f125a
      title: AutobrrNetworkUnhealthy
      for: 2m
      labels:
        severity: critical
        category: logs
      annotations:
        app: "{{ $labels.app }}"
        summary: "{{ $labels.app }} has a unhealthy network"
      condition: A
      data:
        - refId: A
          queryType: instant
          relativeTimeRange:
            from: 600
            to: 0
          datasourceUid: grafanacloud-logs
          model:
            datasource:
              type: loki
              uid: grafanacloud-logs
            editorMode: code
            expr: sum by (app) (count_over_time({service_name="autobrr"} |~ "(?i)network unhealthy"[2m])) > 0
            intervalMs: 1000
            maxDataPoints: 43200
            queryType: instant
            refId: A
      noDataState: NoData
      execErrState: Error
      isPaused: false
      notificationSettings:
        receiver: discord-alerts-channel
