---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-pgdata
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 400Gi
  storageClassName: ceph-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nominatim-project
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-block
