---
originRequest:
  originServerName: "external.zebernst.dev"

ingress:
  - hostname: "zebernst.dev"
    service: https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.zebernst.dev"
    service: https://cilium-gateway-external.kube-system.svc.cluster.local
  - service: http_status:404
