---
originRequest:
  originServerName: "external.zebernst.dev"

ingress:
  - hostname: "zebernst.dev"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.zebernst.dev"
    service: https://ingress-nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
