---
auths:
  public_v1:
    version: 1
  public_v2:
    version: 2

modules:
  # Synology
  #
  # Synology MIBs can be found here:
  #   http://www.synology.com/support/snmp_mib.php
  #   http://dedl.synology.com/download/Document/MIBGuide/Synology_MIB_File.zip
  synology:
    walk:
      - SYNOLOGY-SYSTEM-MIB::synoSystem         # 1.3.6.1.4.1.6574.1
      - SYNOLOGY-DISK-MIB::synoDisk             # 1.3.6.1.4.1.6574.2
      - SYNOLOGY-RAID-MIB::synoRaid             # 1.3.6.1.4.1.6574.3
      - SYNOLOGY-UPS-MIB::synoUPS               # 1.3.6.1.4.1.6574.4
      - SYNOLOGY-SMART-MIB::synologyDiskSMART   # 1.3.6.1.4.1.6574.5
      - SYNOLOGY-SERVICES-MIB::synologyService  # 1.3.6.1.4.1.6574.6
      - SYNOLOGY-STORAGEIO-MIB::storageIO       # 1.3.6.1.4.1.6574.101
      - SYNOLOGY-SPACEIO-MIB::spaceIO           # 1.3.6.1.4.1.6574.102
      - SYNOLOGY-ISCSILUN-MIB::synologyiSCSILUN # 1.3.6.1.4.1.6574.104
    lookups:
      - source_indexes: [ spaceIOIndex ]
        lookup: spaceIODevice
        drop_source_indexes: true
      - source_indexes: [ storageIOIndex ]
        lookup: storageIODevice
        drop_source_indexes: true
      - source_indexes: [ serviceInfoIndex ]
        lookup: serviceName
        drop_source_indexes: true
      - source_indexes: [ diskIndex ]
        lookup: diskID
        drop_source_indexes: true
      - source_indexes: [ raidIndex ]
        lookup: raidName
        drop_source_indexes: true
    overrides:
      SYNOLOGY-DISK-MIB::diskModel:
        type: DisplayString
      SYNOLOGY-DISK-MIB::diskType:
        type: DisplayString
      SYNOLOGY-RAID-MIB::raidFreeSize:
        type: gauge
      SYNOLOGY-RAID-MIB::raidName:
        type: DisplayString
      SYNOLOGY-RAID-MIB::raidTotalSize:
        type: gauge
      SYNOLOGY-SERVICES-MIB::serviceName:
        type: DisplayString
      SYNOLOGY-SMART-MIB::diskSMARTAttrName:
        type: DisplayString
      SYNOLOGY-SMART-MIB::diskSMARTAttrStatus:
        type: DisplayString
      SYNOLOGY-SMART-MIB::diskSMARTInfoDevName:
        type: DisplayString
      SYNOLOGY-SYSTEM-MIB::modelName:
        type: DisplayString
      SYNOLOGY-SYSTEM-MIB::serialNumber:
        type: DisplayString
      SYNOLOGY-SYSTEM-MIB::version:
        type: DisplayString

  # Eaton Network-M2 Card
  # MIBs found at:
  #   https://www.eaton.com/us/en-us/catalog/backup-power-ups-surge-it-power-distribution/eaton-gigabit-network-card---na/network-m2.html
  eaton_xups:
    walk:
      - XUPS-MIB::xupsIdent             # 1.3.6.1.4.1.534.1.1
      - XUPS-MIB::xupsBattery           # 1.3.6.1.4.1.534.1.2
      - UPS-MIB::upsSecondsOnBattery    # 1.3.6.1.2.1.33.1.2.2.0
      - UPS-MIB::upsBatteryTemperature  # 1.3.6.1.2.1.33.1.2.7.0
      - XUPS-MIB::xupsInput             # 1.3.6.1.4.1.534.1.3
      - XUPS-MIB::xupsOutput            # 1.3.6.1.4.1.534.1.4
      - XUPS-MIB::xupsBypass            # 1.3.6.1.4.1.534.1.5
      - XUPS-MIB::xupsAlarm             # 1.3.6.1.4.1.534.1.7
      - XUPS-MIB::xupsTest              # 1.3.6.1.4.1.534.1.8
      - XUPS-MIB::xupsConfig            # 1.3.6.1.4.1.534.1.10
      - XUPS-MIB::xupsRecep             # 1.3.6.1.4.1.534.1.12
    lookups:
      - source_indexes: [ upsAlarmId ]
        lookup: upsAlarmDescr
      - source_indexes: [ xupsAlarmId ]
        lookup: xupsAlarmDescr
      - source_indexes: [ xupsAlarmEventID ]
        lookup: xupsAlarmEventMsg
