---
apiVersion: fission.io/v1
kind: Function
metadata:
  name: ics-proxy
  namespace: fission
spec:
  environment:
    name: python-fastapi
    namespace: fission
  package:
    packageref:
      name: ics-proxy
      namespace: fission
    functionName: main.main
  secrets:
    - name: ics-proxy-secret
      namespace: fission
  InvokeStrategy:
    StrategyType: execution
    ExecutionStrategy:
      ExecutorType: poolmgr
  functionTimeout: 60
  idletimeout: 120
