apiVersion: fission.io/v1
kind: Package
metadata:
  name: ics-proxy
  namespace: fission
spec:
  environment:
    name: python
    namespace: fission
  source:
    type: literal
    literal: "UEsDBBQACAAIAKiynVwAAAAAAAAAAAsEAAAHABwAbWFpbi5weVVUCQADXITyaVyE8ml1eAsAAQQAAAAABAAAAAB9U9FumzAUfecrrqw9mI2QrupDlSqboiUPldJq6sgeFmjkgk2sEsNsoyXK8u+74JCgrRkSyMbnnHvO5SJ0uYGK2XUhX0BuqlJb+Ipb77jW3OuWa2urrScagiiYeYUT5GfNjfU8L+MCNkwq6sPgE9i6KvjSWB2AVDaATKbWbfGRJCMP8EpZwVXGNIw7nZDp3IQ5t5R0h8RvsVKAKu2J4gSaS3NbawXkQRojVQ6fO8gYUFLvMKBmG265JgHcXF0FsD94LdvwFMmrTDYGFN9a2oSnZOgOzFA0kqUifiiRjjjqOzNpqYTM32C6gwvMllrrYiVkwZHYqz8EQfad8UOIINJP3ZFCvpXGGur/E1+QhXpV5S917hCcBdvkN+fkqIf1T6qas2xlmxh+iJ9HVtTFxNFA9wqhtJf4L69HEEa9JKN5VbCUb7iy/5fqAS/Idd23TqudynZcMIsfNmCXT4myyHjWDlZo6heqSaxjtYTYJtgMgvdRpbOocEZ6+GOqoG8+OOkGzU+QmzGCHxbz6H5+/zhzQqwoVhnb9Qs/02n0LZo8Rb+n0exx6i+fR8n7EY2z/e3Bj5Zx9iP58A4NocWPd98n88VsPJ1Es1F83bx0xt4u6PUG4Fg4gOt2xMkXF28Q7SpORkCa3gy7Vt9BumbacDuurRjckoP3B1BLBwg6I6yC9wEAAAsEAABQSwMEFAAIAAgAqbKdXAAAAAAAAAAAagAAAA4AHABweXByb2plY3QudG9tbFVUCQADXoTyaV6E8ml1eAsAAQQAAAAABAAAAAAlykEKgCAUhOH9O4W8dUnSui4iLkIHMshMLfL2Gc3ym1/HdGywxVBYdohJsLe5b/hUphsp+yN8OkglB6aE8/IJrahl/Z95GqVSTA4RwSFYj9xck2jjtZT4cEeGXlBLBwizIk1AXAAAAGoAAABQSwECHgMUAAgACACosp1cOiOsgvcBAAALBAAABwAYAAAAAAABAAAApIEAAAAAbWFpbi5weVVUBQADXITyaXV4CwABBAAAAAAEAAAAAFBLAQIeAxQACAAIAKmynVyzIk1AXAAAAGoAAAAOABgAAAAAAAEAAACkgUgCAABweXByb2plY3QudG9tbFVUBQADXoTyaXV4CwABBAAAAAAEAAAAAFBLBQYAAAAAAgACAKEAAAD8AgAAAAA="
