# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${DB_NAME}-db-role
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${DB_NAME}-db-role
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_USER }}"
        password: "{{ .POSTGRES_PASS }}"
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: ${DB_NAME}
        property: ${OP_USER}
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: ${DB_NAME}
        property: ${OP_PASS}
