---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: goflow2
spec:
  groups:
    - name: goflow2.rules
      rules:
        - alert: GoFlow2DecoderErrors
          expr: sum(rate(flow_decoder_error_total[5m])) > 0
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: GoFlow2 is reporting flow decode errors

        - alert: GoFlow2NoFlowsReceived
          expr: sum(rate(flow_traffic_bytes_total[15m])) == 0
          for: 1h
          labels:
            severity: warning
          annotations:
            summary: GoFlow2 has not received NetFlow/IPFIX records for one hour
