---
endpoints:
  - name: flux-webhook
    url: https://flux-webhook.zebernst.dev/
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover
