---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: onboarding-plex-configmap
    files:
      - resources/wizard/plex/01_welcome.md
      - resources/wizard/plex/02_disclaimers.md
      - resources/wizard/plex/03_download.md
      - resources/wizard/plex/04_requests.md
      - resources/wizard/plex/10_bookmarks.md
      - resources/wizard/plex/99_tips.md
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
