---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: irqbalance
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      irqbalance:
        type: daemonset
        containers:
          app:
            image:
              repository: ghcr.io/buroa/irqbalance
              tag: 1.9.4@sha256:568596c8c4ea34f248fb8798daffda51f3c0047d4bc0921ffd261c970ce1a051
            env:
              IRQBALANCE_BANNED_CPULIST: 12-19 # 12-19 are E-cores
              # ref: https://gist.github.com/gavinmcfall/ea6cb1233d3a300e9f44caf65a32d519#focing-thunderbolt-to-use-intels-performance-cores
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 32Mi
            securityContext:
              privileged: true
    defaultPodOptions:
      hostIPC: true
      hostPID: true
    persistence:
      run:
        type: emptyDir
        globalMounts:
          - path: /run/irqbalance
