---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: whisparr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: whisparr-secret
    template:
      engineVersion: v2
      data:
        WHISPARR__API_KEY: "{{ .WHISPARR_API_KEY }}"
        WHISPARR__POSTGRES__HOST: &dbHost redspot-rw.database.svc.cluster.local
        WHISPARR__POSTGRES__PORT: "5432"
        WHISPARR__POSTGRES__USER: &dbUser "{{ .WHISPARR_POSTGRES_USER }}"
        WHISPARR__POSTGRES__PASSWORD: &dbPass "{{ .WHISPARR_POSTGRES_PASSWORD }}"
        WHISPARR__POSTGRES__MAINDB: &dbName whisparr
        PUSHOVER_TOKEN: "{{ .WHISPARR_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: pushover
    - extract:
        key: whisparr
