# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fission
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/fission/fission
  ref:
    # datasource=github-releases depName=fission/fission
    tag: v1.22.0
