[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     warning
    Parsers_File  /fluent-bit/etc/parsers.conf
    HTTP_Server   Off

[INPUT]
    Name          tail
    Path          /data/flows.log
    Tag           flow.*
    Refresh_Interval 5
    Rotate_Wait   30
    Skip_Long_Lines On

[FILTER]
    Name          modify
    Match         flow.*
    Add           app goflow2
    Add           stream network

[OUTPUT]
    Name          http
    Match         flow.*
    Host          victoria-logs-server.observability.svc.cluster.local
    Port          9428
    URI           /insert/jsonline?_stream_fields=stream,app&_msg_field=log&_time_field=date
    Format        json_lines
    Compress      gzip
    log_response_payload Off
