---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scanopy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: scanopy-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: &dbName scanopy
        INIT_POSTGRES_HOST: &dbHost redspot-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbUser "{{ .SCANOPY_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbPass "{{ .SCANOPY_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        SCANOPY_DATABASE_URL: postgresql://{{ .SCANOPY_POSTGRES_USER }}:{{ .SCANOPY_POSTGRES_PASSWORD }}@redspot-rw.database.svc.cluster.local:5432/scanopy
        SCANOPY_DAEMON_API_KEY: "{{ .SCANOPY_DAEMON_API_KEY }}"
        SCANOPY_NETWORK_ID: "{{ .SCANOPY_NETWORK_ID }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: scanopy
