apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ${APP}-bucket
  namespace: rook-ceph
spec:
  bucketName: ${APP}
  storageClassName: ceph-bucket
  additionalConfig:
    bucketPolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::${APP}/*"
          }
        ]
      }
    bucketLifecycle: |
      {
        "Rules": [
          {
            "ID": "AbortIncompleteMultipartUploads",
            "Status": "Enabled",
            "Prefix": "",
            "AbortIncompleteMultipartUpload": {
              "DaysAfterInitiation": 1
            }
          },
          {
            "ID": "ExpireAfter30Days",
            "Status": "Enabled",
            "Prefix": "",
            "Expiration": {
              "Days": 30
            }
          }
        ]
      }
