# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fission-system
components:
  - ../../components/common
resources:
  - app/ks.yaml
  - functions/ks.yaml
