---
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
    version: v1.12.6
  policy:
    rebootMode: powercycle
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
      expr: status.ceph.health in ['HEALTH_OK']
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      name: redspot
      namespace: database
      expr: status.conditions.filter(c, c.type == "Ready").all(c, c.status == "True")
    - apiVersion: v1
      kind: Node
      expr: |
        status.conditions.filter(c, c.type == "Ready").all(c, c.status == "True")
      timeout: 10m
