# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dawarich-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:17-3.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: dawarich-db-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "50"
      shared_buffers: 128MB
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
