# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dawarich-db
spec:
  instances: 1
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgis
  imageName: ghcr.io/cloudnative-pg/postgis:17-3.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: dawarich-db-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "50"
      shared_buffers: 128MB
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cluster-db-backup/
      endpointURL: https://s3.us-west-001.backblazeb2.com
      serverName: dawarich-db-v1
      s3Credentials:
        accessKeyId:
          name: dawarich-db-secret
          key: aws-access-key-id
        secretAccessKey:
          name: dawarich-db-secret
          key: aws-secret-access-key
