# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dawarich-db-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: dawarich
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dawarich-secret
    template:
      engineVersion: v2
      data:
        DATABASE_HOST: dawarich-db-rw.self-hosted.svc.cluster.local
        DATABASE_PORT: "5432"
        DATABASE_USERNAME: "{{ .POSTGRES_SUPER_USER }}"
        DATABASE_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        DATABASE_NAME: dawarich_production
        REDIS_URL: redis://hindwing.database.svc.cluster.local:6379
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
  dataFrom:
    - extract:
        key: dawarich
