---
apiVersion: fission.io/v1
kind: Environment
metadata:
  name: python-fastapi
  namespace: fission
spec:
  version: 2
  runtime:
    image: ghcr.io/zebernst/fission-python-runtime:latest
  builder:
    image: ghcr.io/zebernst/fission-python-builder:latest
    command: build
  poolsize: 3
