---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-admin-secret
    template:
      data:
        admin-user: "{{ .username }}"
        admin-password: "{{ .password }}"
  dataFrom:
    - extract:
        key: grafana
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-oidc-secret
    template:
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .POCKET_ID_CLIENT_ID }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .POCKET_ID_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: grafana
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: grafana-db-secret
    template:
      engineVersion: v2
      data:
        GF_DATABASE_TYPE: postgres
        GF_DATABASE_HOST: redspot-rw.database.svc.cluster.local:5432
        GF_DATABASE_NAME: grafana
        GF_DATABASE_USER: grafana
        GF_DATABASE_PASSWORD: "{{ .POSTGRES_PASS }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_MAX_OPEN_CONN: "20"
        GF_DATABASE_MAX_IDLE_CONN: "5"
  dataFrom:
    - extract:
        key: grafana
