# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - httproute.yaml
configMapGenerator:
  - name: grafana-logs-taxonomy-dashboard
    files:
      - logs-taxonomy.json=resources/logs-taxonomy.json
    options:
      annotations:
        grafana_folder: "Logs"
      labels:
        grafana_dashboard: "true"
generatorOptions:
  disableNameSuffixHash: true
