---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/common
resources:
  - atuin/ks.yaml
  - hajimari/ks.yaml
  - it-tools/ks.yaml
  - paperless/ks.yaml
