---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - namespace.yaml
  # Flux-Kustomizations
  - atuin/ks.yaml
  - hajimari/ks.yaml
  - it-tools/ks.yaml
  - monica/ks.yaml
  - paperless/ks.yaml
