---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana-operator
      version: v5.13.0
      sourceRef:
        kind: HelmRepository
        name: grafana-oci
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    serviceMonitor:
      enable: true
