---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homebox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homebox-secret
    creationPolicy: Owner
    template:
      data:
        HBOX_DATABASE_HOST: &dbHost redspot-rw.database.svc.cluster.local
        HBOX_DATABASE_PORT: "5432"
        HBOX_DATABASE_USERNAME: &dbUser "{{ .HOMEBOX_POSTGRES_USER }}"
        HBOX_DATABASE_PASSWORD: &dbPass "{{ .HOMEBOX_POSTGRES_PASSWORD }}"
        HBOX_DATABASE_DATABASE: &dbName homebox
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: homebox
    - extract:
        key: cloudnative-pg
