# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homebox
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      homebox:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18
            envFrom: &envFrom
              - secretRef:
                  name: homebox-secret

        containers:
          homebox:
            image:
              repository: ghcr.io/sysadminsmedia/homebox
              # todo: upgrade to v0.22, using main until sysadminsmedia/homebox#986 is officially released
              tag: main@sha256:c70e6466ec80f0a6e8b06d1ab9da9cb6d1aff1f0f72de3ab3c2b14552a42b203
            env:
              TZ: America/Chicago
              HBOX_LOG_LEVEL: info
              HBOX_LOG_FORMAT: json
              HBOX_WEB_MAX_UPLOAD_SIZE: 10
              HBOX_OPTIONS_CHECK_GITHUB_RELEASE: false
              HBOX_DATABASE_DRIVER: postgres
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 64Mi
              limits:
                memory: 256Mi

    defaultPodOptions:
      priorityClassName: internal-only
    service:
      homebox:
        controller: *app
        ports:
          http:
            port: 7745
    ingress:
      tailscale:
        className: tailscale
        hosts:
          - host: &tsHost "{{ .Release.Name }}.kite-harmonic.ts.net"
            paths:
              - path: /
                service:
                  identifier: *app
                  port: http
        tls:
          - hosts:
              - *tsHost

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
