---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monica
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: monica-secret
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .MONICA_APP_KEY }}"
        DB_CONNECTION: pgsql
        DB_HOST: &dbHost redspot16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USERNAME: &dbUser "{{ .MONICA_POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .MONICA_POSTGRES_PASSWORD }}"
        DB_DATABASE: &dbName monica
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: monica
    - extract:
        key: cloudnative-pg
