---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app snmp-exporter
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  path: ./kubernetes/apps/observability/snmp-exporter/app
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: observability
  timeout: 5m
  wait: true
