# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmrule_v1beta1.json
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: node-rules
spec:
  groups:
  - name: node.rules
    rules:
    - expr: topk(1, max(label_replace(kube_pod_info{job="kube-state-metrics",node!=""}, "pod", "$1", "pod", "(.*)")) by(cluster,node,namespace,pod)) by(cluster,namespace,pod)
      record: 'node_namespace_pod:kube_pod_info:'
      labels:
        job: node-exporter
    - expr: count(node_cpu_seconds_total{mode="idle",job="cluster"} * on(cluster,namespace,pod) group_left(node) topk(1, node_namespace_pod:kube_pod_info:) by(cluster,namespace,pod)) by(cluster,node)
      record: node:node_num_cpu:sum
      labels:
        job: node-exporter
    - expr: sum(node_memory_MemAvailable_bytes{job="cluster"} or (((node_memory_Buffers_bytes{job="cluster"} + node_memory_Cached_bytes{job="cluster"}) + node_memory_MemFree_bytes{job="cluster"}) + node_memory_Slab_bytes{job="cluster"})) by(cluster)
      record: :node_memory_MemAvailable_bytes:sum
      labels:
        job: node-exporter
    - expr: avg(sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal",job="cluster"}[5m])) without(mode)) by(cluster,node)
      record: node:node_cpu_utilization:ratio_rate5m
      labels:
        job: node-exporter
    - expr: avg(node:node_cpu_utilization:ratio_rate5m) by(cluster)
      record: cluster:node_cpu:ratio_rate5m
      labels:
        job: node-exporter
