---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmprobe_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: devices
spec:
  interval: 1m
  module: icmp
  vmProberSpec:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    static:
      targets:
        - unifi
        - nas.internal
        - ups.internal
        - homeassistant.internal
