# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        database: |
          DB_TYPE=postgres
          HOST=redspot-rw.database.svc.cluster.local:5432
          NAME=forgejo
          USER={{ .POSTGRES_USER }}
          PASSWD={{ .POSTGRES_PASS }}
          SSL_MODE=disable
        security: |
          INTERNAL_TOKEN={{ .INTERNAL_TOKEN }}
          SECRET_KEY={{ .SECRET_KEY }}
          INSTALL_LOCK=true
        oauth2: |
          JWT_SECRET={{ .JWT_SECRET }}
        server: |
          LFS_JWT_SECRET={{ .LFS_JWT_SECRET }}
  dataFrom:
    - extract:
        key: forgejo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oauth
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-oauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        key: "{{ .POCKET_ID_CLIENT_ID }}"
        secret: "{{ .POCKET_ID_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: forgejo
