# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmrule_v1beta1.json
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: kubernetes-system-scheduler
spec:
  groups:
  - name: kubernetes-system-scheduler
    rules:
    - alert: KubeSchedulerDown
      expr: absent(up{job="kube-scheduler"})
      annotations:
        description: KubeScheduler has disappeared from Prometheus target discovery.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeschedulerdown
        summary: Target disappeared from Prometheus target discovery.
      condition: null
      for: 15m
      labels:
        severity: critical
        job: kube-scheduler
      keep_firing_for: 90s
    - alert: KubeSchedulerInstanceUnreachable
      expr: up{job="kube-scheduler"} == 0
      annotations:
        description: A KubeScheduler instance has been unreachable for more than 15 minutes.
        runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeschedulerinstanceunreachable
        summary: KubeScheduler instance is unreachable.
      for: 15m
      labels:
        severity: warning
        job: kube-scheduler
      keep_firing_for: 90s
