---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: zebernst-dev-tls
spec:
  externalSecretName: zebernst-dev-tls
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: [ "cert-manager", "network" ]
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: "0"
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    target:
      name: zebernst-dev-tls
      creationPolicy: Orphan
      template:
        engineVersion: v2
        type: kubernetes.io/tls
        metadata:
          annotations:
            cert-manager.io/alt-names: '*.zebernst.dev,zebernst.dev'
            cert-manager.io/certificate-name: zebernst-dev
            cert-manager.io/common-name: zebernst.dev
            cert-manager.io/ip-sans: ""
            cert-manager.io/issuer-group: ""
            cert-manager.io/issuer-kind: ClusterIssuer
            cert-manager.io/issuer-name: letsencrypt-production
            cert-manager.io/uri-sans: ""
          labels:
            controller.cert-manager.io/fao: "true"
    dataFrom:
      - extract:
          key: zebernst-dev-tls
          decodingStrategy: Auto
