# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - helmrelease.yaml
  - daemon-helmrelease.yaml
  - bootstrap-helmrelease.yaml
configMapGenerator:
  - name: scanopy-snmp-bootstrap
    files:
      - bootstrap-snmp.py=./resources/bootstrap-snmp.py
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
