---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: donetick
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: donetick-secret
    creationPolicy: Owner
    template:
      data:
        DT_JWT_SECRET: "{{ .DONETICK_JWT_SECRET }}"
        DT_PUSHOVER_TOKEN: "{{ .DONETICK_PUSHOVER_TOKEN }}"
        DT_DATABASE_HOST: &dbHost redspot16-rw.database.svc.cluster.local
        DT_DATABASE_PORT: "5432"
        DT_DATABASE_USER: &dbUser "{{ .DONETICK_POSTGRES_USER }}"
        DT_DATABASE_PASSWORD: &dbPass "{{ .DONETICK_POSTGRES_PASS }}"
        DT_DATABASE_NAME: &dbName donetick
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: donetick
    - extract:
        key: cloudnative-pg
    - extract:
        key: pushover
