---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${MC_BACKUP_ACCESSMODES:=ReadWriteOnce}"]
  resources:
    requests:
      storage: "${MC_BACKUP_CAPACITY:=5Gi}"
  storageClassName: "${MC_BACKUP_STORAGECLASS:=ceph-block}"
