---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmrule_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: blackbox-exporter
spec:
  groups:
    - name: blackbox-exporter.rules
      rules:
        - alert: BlackboxInstanceDown
          expr: |
            probe_success == 0
          for: 5m
          keep_firing_for: 90s
          annotations:
            summary: >-
              The host {{ $labels.instance }} is down
          labels:
            severity: critical
