# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pocket-id-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APP_URL: "https://id.zebernst.dev"
        TRUST_PROXY: "true"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        DB_CONNECTION_STRING: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@redspot-rw.database.svc.cluster.local:5432/pocket-id"
        INIT_POSTGRES_DBNAME: pocket-id
        INIT_POSTGRES_HOST: redspot-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: pocket-id
    - extract:
        key: cloudnative-pg
