---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zebernst-dev
spec:
  secretName: zebernst-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: zebernst.dev
  dnsNames:
    - zebernst.dev
    - "*.zebernst.dev"
