# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmrule_v1beta1.json
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: victoria-metrics-custom
spec:
  groups:
    - name: dockerhub
      rules:
        - alert: DockerhubRateLimitRisk
          annotations:
            summary: >-
              There are {{ $value }} containers pulling from Dockerhub. This may lead to rate limiting.
          expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
          for: 5m
          keep_firing_for: 90s
          labels:
            severity: critical
            job: cadvisor
    - name: oom
      rules:
        - alert: OomKilled
          annotations:
            summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
          expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
          for: 5m
          keep_firing_for: 90s
          labels:
            severity: critical
            job: kubernetes-apps
