# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - custom.yaml
  - general.yaml
  - kube-state-metrics.yaml
  - kubelet.yaml
  - node/
  - recording/
  - vmstack/
  - workloads/
