---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: your-spotify
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: your-spotify-secret
    template:
      engineVersion: v2
      data:
        MONGO_ENDPOINT: mongodb://ferretdb.database.svc.cluster.local:27017/your_spotify
        SPOTIFY_PUBLIC: "{{ .YOUR_SPOTIFY_CLIENT_ID }}"
        SPOTIFY_SECRET: "{{ .YOUR_SPOTIFY_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: your-spotify
