---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: your-spotify
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      server:
        enabled: true
        type: deployment
        strategy: &strategy RollingUpdate
        rollingUpdate: &rollingUpdate
          unavailable: 0
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: yooooomi/your_spotify_server
              tag: 1.11.0
              pullPolicy: IfNotPresent
            env:
              API_ENDPOINT: &api_url https://spotify.zebernst.dev/api
              CLIENT_ENDPOINT: https://spotify.zebernst.dev
              MONGO_NO_ADMIN_RIGHTS: "true"
              PORT: &port 80
              TIMEZONE: ${TZ}
              COOKIE_VALIDITY: 24h
            envFrom:
              - secretRef:
                  name: your-spotify-secret
            probes: &probes
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ['ALL']
            resources:
              requests:
                cpu: 10m
                memory: 550Mi
              limits:
                memory: 775Mi
      web:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: *strategy
        rollingUpdate: *rollingUpdate
        containers:
          app:
            image:
              repository: yooooomi/your_spotify_client
              tag: 1.11.0
            env:
              API_ENDPOINT: *api_url
              PORT: *port
            probes: *probes
            securityContext: *securityContext
    service:
      server:
        controller: server
        nameOverride: server
        primary: true
        ports:
          http:
            port: *port
      web:
        controller: web
        nameOverride: web
        ports:
          http:
            port: *port
    ingress:
      external:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.zebernst.dev
          nginx.ingress.kubernetes.io/proxy-body-size: 50m
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/rewrite-target: /$2
        hosts:
          - host: spotify.zebernst.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: web
                  port: http
              - path: /api(/|$)(.*)
                pathType: Prefix
                service:
                  identifier: server
                  port: http
