# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/generators.external-secrets.io/password_v1alpha1.json
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: mariadb-metrics
spec:
  length: 32
  symbols: 0
  allowRepeat: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-metrics
spec:
  refreshPolicy: CreatedOnce
  target:
    name: mariadb-metrics
    immutable: true
    template:
      engineVersion: v2
      data:
        mariadb-metrics-password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: mariadb-metrics
