# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: talos-backup-s3
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: barman-b2-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: barman-b2-credentials
        property: AWS_SECRET_ACCESS_KEY
