# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dnsendpoint.yaml
  - externalsecret.yaml
  - helmrelease.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: atm10-bluemap-configs
    files:
      - bluemap/core.conf
      - bluemap/webapp.conf
      - bluemap/webserver.conf
  - name: atm10-bluemap-maps
    files:
      - bluemap/maps/atm10-overworld.conf
      - bluemap/maps/atm10-nether.conf
      - bluemap/maps/atm10-end.conf
      - bluemap/maps/atm10-aether.conf
      - bluemap/maps/atm10-twilight-forest.conf
      - bluemap/maps/atm10-undergarden.conf
      - bluemap/maps/atm10-bumblezone.conf
      - bluemap/maps/atm10-eternal-starlight.conf
      - bluemap/maps/atm10-deeper-darker.conf
      - bluemap/maps/atm10-ice-and-fire.conf
      - bluemap/maps/atm10-allthemodium-mining.conf
      - bluemap/maps/atm10-allthemodium-other.conf
      - bluemap/maps/atm10-allthemodium-beyond.conf
  - name: atm10-gatus-ep
    files:
      - config.yaml=gatus-config.yaml
    options:
      labels:
        gatus.io/enabled: "true"
