---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tracearr-db-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: tracearr
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr-db-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tracearr-db-backup-secret
  data:
    - secretKey: aws-access-key-id
      remoteRef:
        key: barman-b2-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: barman-b2-credentials
        property: AWS_SECRET_ACCESS_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tracearr-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://{{ .POSTGRES_SUPER_USER }}:{{ .POSTGRES_SUPER_PASS }}@tracearr-db-rw.media.svc.cluster.local:5432/tracearr"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        COOKIE_SECRET: "{{ .COOKIE_SECRET }}"
  dataFrom:
    - extract:
        key: tracearr
