# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-dns-egress.yaml
  - allow-prometheus-scrape-ingress.yaml
  - allow-metrics-server-egress.yaml
  - allow-gateway-ingress.yaml
