---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmprobe_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: radicale
spec:
  interval: 1m
  module: tcp_connect
  vmProberSpec:
    url: blackbox-exporter.observability.svc.cluster.local:9115
  targets:
    static:
      targets:
        - radicale.self-hosted.svc.cluster.local:5232
