---
apiVersion: fission.io/v1
kind: Package
metadata:
  name: ics-on-call
  namespace: fission
spec:
  environment:
    name: python
    namespace: fission
  source:
    type: literal
    literal: UEsDBBQACAAIAIkTmFwAAAAAAAAAAB8DAAAHABwAY29kZS5weVVUCQADQdXqaUHV6ml1eAsAAQQAAAAABAAAAACtUU1Lw0AQvedXDOtlF5NUxIJUeioKheqhticrZU0mdiXZLLsTbBH/u9MkSqAePLgQmM28j30zpnK1J6hDZLrKY/Rd7ojcPoqiHAuotLFSTSLgEzDzSGGbGw9TEKP+PipMCKa2YgDaWl0hgyzuSRpCL+uQliYQc+VARyk1ZDlNO2Yx9lilbzWbD9DxUF1FLfPdMKV2aOUvrFYwBtG4QB51lTS+FEqBDlB0mY6Hf7JpkTIilyplqHFS/V09NFWl/SHhKye1pwZ9419MPLpSZ1ihpVOjQfM3sxaX1Za6frvn9BVJ8gRUSryrDnIGa1vUZQ7z2SOUxmJLMrbRxHsOIJd3MxiPr8YTmC0Xd3AOwbHtiPRLl6hp6Zizicc0NC/Si43f2CfY0LPgNPz17+gIHo8rHeD7kcXDSPGPbgxFqV/DlMH368Vqvpg/3PbxeGQNj7oXjOHy4iKGDzHr3JLVwaGYgDiGHWW6RJtrfwPZTvuANG2oSK7FZ/QFUEsHCAnyFSJ4AQAAHwMAAFBLAwQUAAgACACKE5hcAAAAAAAAAABsAAAADgAcAHB5cHJvamVjdC50b21sVVQJAAND1eppQ9XqaXV4CwABBAAAAAAEAAAAACXJQQ5AMBBG4f2copm1NhprLiIWUn+iwrTaEm6PeMvv9TGFBa4MJOMG1Sr2Lusg2o3rynQiZR/k89pYUzMl7IdPyDreZf5P1zbGWqYJETJBnEd+vSf1xnMp8eKKBnoAUEsHCL06fCRfAAAAbAAAAFBLAQIeAxQACAAIAIkTmFwJ8hUieAEAAB8DAAAHABgAAAAAAAEAAACkgQAAAABjb2RlLnB5VVQFAANB1eppdXgLAAEEAAAAAAQAAAAAUEsBAh4DFAAIAAgAihOYXL06fCRfAAAAbAAAAA4AGAAAAAAAAQAAAKSByQEAAHB5cHJvamVjdC50b21sVVQFAAND1eppdXgLAAEEAAAAAAQAAAAAUEsFBgAAAAACAAIAoQAAAIACAAAAAA==
