# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
components:
  - ../../components/common
resources:
  - atuin/ks.yaml
  - dawarich/ks.yaml
  - glance/ks.yaml
  - hajimari/ks.yaml
  - it-tools/ks.yaml
  - nocodb/ks.yaml
  - nominatim/ks.yaml
  - paperless/ks.yaml
  - rxresume/ks.yaml
  - unwrapped/ks.yaml
