---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: self-hosted
components:
  - ../../components/common
resources:
  - atuin/ks.yaml
  - hajimari/ks.yaml
  - homebox/ks.yaml
  - it-tools/ks.yaml
  - mealie/ks.yaml
  - nocodb/ks.yaml
  - paperless/ks.yaml
  - radicale/ks.yaml
  - rxresume/ks.yaml
  - trmnl/ks.yaml
