---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app synology-csi-driver
  namespace: &ns kube-system
spec:
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: kubernetes/apps/kube-system/synology-csi-driver/app
  prune: true
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: snapshot-controller
      namespace: *ns
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
