---
alerting:
  pushover:
    application-token: ${GATUS_PUSHOVER_APP_TOKEN}
    user-key: ${GATUS_PUSHOVER_USER_KEY}
    priority: 1
    resolved-priority: 0
    default-alert:
      description: health-check failed
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints: []

metrics: true

storage:
  type: postgres
  path: postgres://${INIT_POSTGRES_USER}:${INIT_POSTGRES_PASS}@${INIT_POSTGRES_HOST}:5432/${INIT_POSTGRES_DBNAME}?sslmode=disable
  caching: true

ui:
  title: Status | Gatus
  header: Status
  logo: https://github.com/user-attachments/assets/0248f379-cc4a-4a59-a400-014a750c61fa
  link: https://github.com/zebernst
  buttons:
    - name: Github
      link: https://github.com/zebernst
    - name: Homelab
      link: https://github.com/zebernst/homelab

web:
  port: ${GATUS_WEB_PORT}
