# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app grafana-db
  namespace: &ns database
spec:
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: *ns
    - name: onepassword
      namespace: external-secrets
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: DatabaseRole
      failed: status.applied == false
      current: status.applied == true
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      failed: status.applied == false
      current: status.applied == true
  interval: 30m
  retryInterval: 1m
  path: kubernetes/apps/database/grafana-db/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true
