---
clusterName: &cluster jupiter
clusterPodNets: ["10.244.0.0/16"]
clusterSvcNets: ["10.245.0.0/16"]
additionalApiServerCertSans: ["127.0.0.1"]
additionalMachineCertSans: ["127.0.0.1"]
endpoint: https://k8s.internal:6443
kubernetesVersion: ${KUBERNETES_VERSION}
talosVersion: ${TALOS_VERSION}

nodes:
  - hostname: io.k8s.internal
    ipAddress: 192.168.10.10
    controlPlane: true
    installDiskSelector:
      serial: 50026B728363711A
    machineDisks: []
    networkInterfaces:
      - &bond0
        interface: bond0
        bond:
          mode: 802.3ad
          xmitHashPolicy: layer3+4
          lacpRate: fast
          miimon: 1000
          deviceSelectors: [{ hardwareAddr: "58:47:ca:7a:*", driver: igc }]
        dhcp: true
        mtu: 9000
        vlans:
          - { vlanId: 20, dhcp: false, mtu: 1500 }
          - { vlanId: 30, dhcp: false, mtu: 1500 }

  - hostname: ganymede.k8s.internal
    ipAddress: 192.168.10.11
    controlPlane: true
    installDiskSelector:
      serial: 50026B728363E11C
    machineDisks: []
    networkInterfaces:
      - <<: *bond0

  - hostname: callisto.k8s.internal
    ipAddress: 192.168.10.12
    controlPlane: true
    installDiskSelector:
      serial: 50026B7283636BA1
    machineDisks: []
    networkInterfaces:
      - <<: *bond0

controlPlane:
  noSchematicValidate: true

  schematic:
    customization:
      extraKernelArgs:
        - apparmor=0               # Less security, faster 'puter
        - init_on_alloc=0          # Less security, faster 'puter
        - init_on_free=0           # Less security, faster 'puter
        - intel_iommu=on           # PCI Passthrough
        - iommu=pt                 # PCI Passthrough
        - mitigations=off          # Less security, faster 'puter
        - security=none            # Less security, faster 'puter
        - talos.auditd.disabled=1  # Less security, faster 'puter

      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/iscsi-tools
          - siderolabs/mei
          - siderolabs/thunderbolt


  nodeLabels:
    topology.kubernetes.io/region: *cluster
    topology.kubernetes.io/zone: m

  patches:
    - "@./patches/cluster.yaml"
    - "@./patches/machine.yaml"
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl
    - |-
      - op: remove
        path: /cluster/apiServer/auditPolicy
