---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: unpackerr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unpackerr
      app.kubernetes.io/instance: unpackerr
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
