---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./gatus/ks.yaml
  - ./grafana-k8s-monitoring/ks.yaml
  - ./grafana-operator/ks.yaml
  - ./unpoller/ks.yaml
