# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - blackbox-exporter/ks.yaml
  - gatus/ks.yaml
  - grafana/ks.yaml
  - karma/ks.yaml
  - keda/ks.yaml
  - kromgo/ks.yaml
  - victoria-metrics/ks.yaml
  - fluent-bit/ks.yaml
  - goflow2/ks.yaml
  - syslog-collector/ks.yaml
  - victoria-logs/ks.yaml
  - vmalert/ks.yaml
  - silence-operator/ks.yaml
  - smartctl-exporter/ks.yaml
  - snmp-exporter/ks.yaml
  - unpoller/ks.yaml
