---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - gatus/ks.yaml
  - grafana/ks.yaml
  - kromgo/ks.yaml
  - kube-prometheus-stack/ks.yaml
  - loki/ks.yaml
  - promtail/ks.yaml
  - snmp-exporter/ks.yaml
  - unpoller/ks.yaml
