---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 500Gi
  storageClassName: iscsi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-optimized-media
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1.5Ti
  storageClassName: iscsi
