---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maddy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: maddy-secret
    creationPolicy: Owner
    template:
      data:
        dkim_key.pem: "{{ .DKIM_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: maddy
