# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app maddy
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      *app:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          *app:
            image:
              repository: docker.io/foxcpp/maddy
              tag: 0.8
            envFrom:
              - secretRef:
                  name: maddy-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 25
                  initialDelaySeconds: 10
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 25
                  initialDelaySeconds: 5
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      *app:
        controller: *app
        ports:
          smtp:
            port: &smtpPort 25
          submission:
            port: &submissionPort 587
          metrics:
            port: &metricsPort 9749

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    persistence:
      config:
        type: configMap
        name: maddy-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
      state:
        type: emptyDir
        globalMounts:
          - path: /var/lib/maddy
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
