---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mealie-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_SERVER: &dbHost redspot-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .MEALIE_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .MEALIE_POSTGRES_PASS }}"
        POSTGRES_DB: &dbName mealie
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: mealie
    - extract:
        key: cloudnative-pg
