# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - vmservicescrape.yaml
configMapGenerator:
  - name: syslog-collector-configmap
    files:
      - fluent-bit.conf=resources/fluent-bit.conf
generatorOptions:
  disableNameSuffixHash: true
