# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prometheus-secret
    template:
      engineVersion: v2
      data:
        host: "https://{{ .PROMETHEUS_HOST }}"
        username: "{{ .PROMETHEUS_USER }}"
        password: "{{ .GRAFANA_CLOUD_API_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana-cloud-prometheus
    - extract:
        key: grafana-cloud
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    template:
      engineVersion: v2
      data:
        host: "https://{{ .LOKI_HOST }}"
        username: "{{ .LOKI_USER }}"
        password: "{{ .GRAFANA_CLOUD_API_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana-cloud-loki
    - extract:
        key: grafana-cloud
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tempo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tempo-secret
    template:
      engineVersion: v2
      data:
        host: "https://{{ .TEMPO_HOST }}"
        username: "{{ .TEMPO_USER }}"
        password: "{{ .GRAFANA_CLOUD_API_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana-cloud-tempo
    - extract:
        key: grafana-cloud
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        host: "https://{{ .ALERTMANAGER_HOST }}"
        username: "{{ .ALERTMANAGER_USER }}"
        password: "{{ .GRAFANA_CLOUD_API_TOKEN }}"
  dataFrom:
    - extract:
        key: grafana-cloud-alertmanager
    - extract:
        key: grafana-cloud
