# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-prometheus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-prometheus-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: host
      remoteRef:
        key: grafanacloud-prometheus-credentials
        property: host
    - secretKey: username
      remoteRef:
        key: grafanacloud-prometheus-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-loki-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: host
      remoteRef:
        key: grafanacloud-loki-credentials
        property: host
    - secretKey: username
      remoteRef:
        key: grafanacloud-loki-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-tempo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-tempo-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: host
      remoteRef:
        key: grafanacloud-tempo-credentials
        property: host
    - secretKey: username
      remoteRef:
        key: grafanacloud-tempo-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-alertmanager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-alertmanager-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: host
      remoteRef:
        key: grafanacloud-alertmanager-credentials
        property: host
    - secretKey: username
      remoteRef:
        key: grafanacloud-alertmanager-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
