# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-prometheus-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-prometheus-secret
  dataFrom:
    - extract:
        key: grafanacloud-prometheus-credentials
  data:
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-loki-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-loki-secret
  dataFrom:
    - extract:
        key: grafanacloud-loki-credentials
  data:
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-tempo-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-tempo-secret
  dataFrom:
    - extract:
        key: grafanacloud-tempo-credentials
  data:
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafanacloud-alertmanager-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafanacloud-alertmanager-secret
  dataFrom:
    - extract:
        key: grafanacloud-alertmanager-credentials
  data:
    - secretKey: password
      remoteRef:
        key: grafanacloud-alloy-token
        property: credential
