---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cluster:
      name: ${CLUSTER_NAME}

    destinations:
      - name: cloudMetrics
        type: prometheus
        url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
        auth:
          type: basic
        secret:
          create: false
          name: prometheus-secret
        metricProcessingRules: |-
          write_relabel_config {
            source_labels = ["namespace","pod"]
            separator = "@"
            regex = "flux-system@(.+)-.+-.+"
            target_label = "uid"
            replacement = ""
          }
          write_relabel_config {
            source_labels = ["namespace","pod"]
            separator = "@"
            regex = "flux-system@(.+)-.+-.+"
            target_label = "pod"
            replacement = "$1"
          }

      - name: cloudLogs
        type: loki
        url: https://logs-prod-006.grafana.net/loki/api/v1/push
        auth:
          type: basic
        secret:
          create: false
          name: loki-secret

      - name: cloudTraces
        type: otlp
        url: https://tempo-prod-04-prod-us-east-0.grafana.net/tempo/v1/traces
        auth:
          type: basic
        secret:
          create: false
          name: tempo-secret

    clusterMetrics:
      enabled: true
    clusterEvents:
      enabled: true
    nodeLogs:
      enabled: false # talos doesn't allow this
    podLogs:
      enabled: true
      gatherMethod: kubernetesApi
    selfReporting:
      enabled: false

    prometheusOperatorObjects:
      enabled: true
      crds:
        deploy: true

    alloy-metrics:
      enabled: true
    alloy-logs:
      enabled: true
      controller:
        type: deployment # DaemonSet not necessary without nodeLogs
    alloy-singleton:
      enabled: true
