---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: 1.5.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    cluster:
      name: ${CLUSTER_NAME}
    externalServices:
      prometheus:
        secret:
          create: false
          name: prometheus-secret
      loki:
        secret:
          create: false
          name: loki-secret
      tempo:
        secret:
          create: false
          name: tempo-secret
    metrics:
      enabled: true
      cost:
        enabled: false
      node-exporter:
        enabled: true
      kepler:
        enabled: false
    logs:
      enabled: true
      pod_logs:
        enabled: true
      cluster_events:
        enabled: true
    traces:
      enabled: true
    receivers:
      grpc:
        enabled: true
      http:
        enabled: true
      zipkin:
        enabled: true
      grafanaCloudMetrics:
        enabled: true
    opencost:
      enabled: false
    kube-state-metrics:
      enabled: true
    prometheus-node-exporter:
      enabled: true
    prometheus-operator-crds:
      enabled: true
    alloy: {}
    alloy-events: {}
    alloy-logs: {}
