---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stash
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: stash-secret
    template:
      engineVersion: v2
      data:
        config.py: |
          stashconfig = {
              "scheme": "http",
              "Host": "localhost",
              "Port": "9999",
              "ApiKey": "{{ .API_KEY }}",
          }
          success_tag = "[SHA: Scraped]"
          failure_tag = "[SHA: No Match]"
          disable_nfkd = False
  dataFrom:
    - extract:
        key: stash
