---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stash
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          stash:
            image:
              repository: ghcr.io/feederbox826/stash-s6
              tag: hwaccel-alpine-2025-08-08@sha256:504d262b0f49d43440a22119f4f4a784ba5c91868bf43241ea4e480b3fd43f81
              pullPolicy: IfNotPresent
            env:
              TZ: America/Chicago
              PUID: 568
              STASH_CONFIG_FILE: /config/config.yml
              STASH_STASH: /media/xxx/
              STASH_GENERATED: /generated/
              STASH_METADATA: /metadata/
              STASH_CACHE: /cache/
              STASH_PORT: &port 9999
              STASH_EXTERNAL_HOST: https://stash.kite-harmonic.ts.net

            probes:
              liveness: &probe
                enabled: true
              readiness: *probe
              startup: *probe
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 1Gi
              limits:
                memory: 12Gi
                gpu.intel.com/i915: 1
          chrome:
            image:
              repository: chromedp/headless-shell
              tag: 141.0.7390.16
            args:
              - --enable-unsafe-swiftshader
            probes:
              liveness: &probe
                enabled: true
              readiness: *probe
              startup: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: [ "ALL" ] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [65568]
    service:
      app:
        controller: app
        ports:
          http:
            port: *port
    ingress:
      ts:
        className: tailscale
        hosts:
          - host: &host "{{ .Release.Name }}.kite-harmonic.ts.net"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        existingClaim: stash
        globalMounts:
          - path: /config
            subPath: config
          - path: /blobs
            subPath: blobs
      cache:
        enabled: true
        existingClaim: stash-cache
        globalMounts:
          - path: /cache
            subPath: cache
          - path: /generated
            subPath: generated
          - path: /metadata
            subPath: metadata
          - path: /pip-install
            subPath: pip
      media:
        type: nfs
        server: nas.internal
        path: /volume1/media
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
