---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ferretdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ferretdb-secret
    template:
      engineVersion: v2
      data:
        FERRETDB_POSTGRESQL_URL: postgresql://{{ .FERRETDB_POSTGRES_USER }}:{{ .FERRETDB_POSTGRES_PASS }}@redspot16-rw.database.svc.cluster.local:5432/ferretdb
        FERRETDB_TEST_ENABLE_NEW_AUTH: "true"
        FERRETDB_SETUP_USERNAME: "{{ .FERRETDB_INIT_USER }}"
        FERRETDB_SETUP_PASSWORD: "{{ .FERRETDB_INIT_PASS }}"
        FERRETDB_SETUP_DATABASE: ferret
        INIT_POSTGRES_DBNAME: ferretdb
        INIT_POSTGRES_HOST: redspot16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .FERRETDB_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .FERRETDB_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: ferretdb
    - extract:
        key: cloudnative-pg
