# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio-v3
spec:
  scheme: HTTPS
  staticConfigs:
    - targets:
        - minio.zebernst.dev
  metricsPath: /minio/metrics/v3
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio-cluster
spec:
  scheme: HTTPS
  staticConfigs:
    - targets:
        - minio.zebernst.dev
  metricsPath: /minio/v2/metrics/cluster
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio-bucket
spec:
  scheme: HTTPS
  staticConfigs:
    - targets:
        - minio.zebernst.dev
  metricsPath: /minio/v2/metrics/bucket
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name minio-resource
spec:
  scheme: HTTPS
  staticConfigs:
    - targets:
        - minio.zebernst.dev
  metricsPath: /minio/v2/metrics/resource
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
