---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: smartctl-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter
      app.kubernetes.io/instance: smartctl-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      relabelConfigs:
        - action: labeldrop
          regex: (pod)
