---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kromgo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kromgo-secret
    template:
      engineVersion: v2
      data:
        PROMETHEUS_URL: |-
          https://{{ .PROMETHEUS_USER }}:{{ .GRAFANA_CLOUD_API_TOKEN }}@{{ .PROMETHEUS_HOST }}
  dataFrom:
    - extract:
        key: grafana-cloud-prometheus
    - extract:
        key: grafana-cloud
