---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: snmp-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: snmp-exporter-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: snmp-exporter-modules
            items:
              - key: modules.yaml
                templateAs: Values
      data:
        snmp.yaml: |
          auths:
            public_v1:
              community: {{ .UNIFI_SNMP_COMMUNITY | quote }}
              security_level: noAuthNoPriv
              auth_protocol: MD5
              priv_protocol: DES
              version: 1
            public_v2:
              community: {{ .UNIFI_SNMP_COMMUNITY | quote }}
              security_level: noAuthNoPriv
              auth_protocol: MD5
              priv_protocol: DES
              version: 2
          {{ .modules_yaml }}
  dataFrom:
    - extract:
        key: scanopy
