# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 9.12.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  values:
    fullnameOverride: *app
    extraArgs:
      - "--config.file=/config/snmp.yaml"
    extraSecretMounts:
      - name: snmp-exporter-config
        mountPath: /config/snmp.yaml
        subPath: snmp.yaml
        secretName: snmp-exporter-config
        readOnly: true
    podAnnotations:
      secret.reloader.stakater.com/reload: snmp-exporter-config
    serviceMonitor:
      enabled: true
      scrapeTimeout: 30s
      params:
        - name: nas
          auth: [public_v2]
          module: [synology]
          target: nas.internal
          scrapeTimeout: 30s
        - name: ups
          auth: [public_v1]
          module: [eaton_xups]
          target: ups.internal
          scrapeTimeout: 30s
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
