---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: snmp-exporter
spec:
  groups:
    - name: snmp-exporter.rules
      rules:
        - alert: UPSOnBattery
          expr: |
            (xupsBatTimeRemaining/60 <= 20 and upsSecondsOnBattery > 0)
          annotations:
            summary: >
              UPS {{ $labels.instance }} is running on battery power and has less than {{ $value }} minutes of runtime remaining
          for: 5m
          labels:
            severity: critical
