# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-runner-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .RUNNER_REGISTRATION_TOKEN }}"
  dataFrom:
    - extract:
        key: forgejo
