# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &db radarr-db
  namespace: &ns downloads
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *db
  dependsOn:
    - name: cloudnative-pg-cluster
      namespace: database
    - name: onepassword
      namespace: external-secrets
  path: kubernetes/apps/downloads/radarr/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: radarr
      OP_USER: RADARR_POSTGRES_USER
      OP_PASS: RADARR_POSTGRES_PASSWORD
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
    - apiVersion: postgresql.cnpg.io/v1
      kind: DatabaseRole
      failed: has(status.applied) && !status.applied
      current: has(status.applied) && status.applied && status.observedGeneration == metadata.generation
    - apiVersion: postgresql.cnpg.io/v1
      kind: Database
      failed: has(status.applied) && !status.applied
      current: has(status.applied) && status.applied && status.observedGeneration == metadata.generation
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr
  namespace: &ns downloads
spec:
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/keda/nfs-scaler
    - ../../../../../components/vmalert-rules
  dependsOn:
    - name: radarr-db
    - name: onepassword
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  path: kubernetes/apps/downloads/radarr/app/hd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr-uhd
  namespace: &ns downloads
spec:
  targetNamespace: *ns
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/keda/nfs-scaler
    - ../../../../../components/vmalert-rules
  dependsOn:
    - name: radarr-db
    - name: onepassword
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  path: kubernetes/apps/downloads/radarr/app/uhd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
