---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calibre-web-automated
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cwa-secret
    template:
      engineVersion: v2
      data:
        HARDCOVER_TOKEN: "{{ .API_TOKEN }}"
  dataFrom:
    - extract:
        key: hardcover
