---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
#      securityContext:
#        runAsNonRoot: true
#        runAsUser: 568
#        runAsGroup: 568
#        fsGroup: 568
#        fsGroupChangePolicy: OnRootMismatch
#        supplementalGroups: [ 65568 ]

    controllers:
      calibre-web:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: crocodilestick/calibre-web-automated
              tag: V3.0.4
            env:
              CACHE_DIR: /cache
              CALIBRE_PORT: &port 8083
              TZ: America/New_York
              PUID: 568
              PGID: 65568
              DOCKER_MODS: >-
                {{- $items := list
                  "// renovate: lsio-docker-mod"
                  "ghcr.io/linuxserver/mods:universal-calibre-v7.16.0"
                -}}
                {{- $filtered := list -}}
                {{- range $item := $items -}}
                  {{- if not (hasPrefix "//" $item) -}}
                    {{- $filtered = append $filtered $item -}}
                  {{- end -}}
                {{- end -}}
                {{- $filtered | join "|" -}}

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  initialDelaySeconds: 60
                  failureThreshold: 45
                  periodSeconds: 5
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 768Mi

    service:
      app:
        controller: calibre-web
        primary: true
        ports:
          http:
            port: 80
            targetPort: *port
      # ref: https://github.com/janeczku/calibre-web/issues/1470
      # Kobo doesn't support direct https access for certain endpoints, and as of now
      # Tailscale doesn't allow injecting custom ingress headers (X-Scheme: https).
      # Workaround: expose http for API access
      api:
        controller: calibre-web
        type: LoadBalancer
        loadBalancerClass: tailscale
        annotations:
          tailscale.com/hostname: calibre-web-api
        ports:
          http:
            port: 80
            targetPort: *port

    ingress:
      ts:
        className: tailscale
        hosts:
          - host: &tsHost calibre.kite-harmonic.ts.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *tsHost

    persistence:
      config:
        existingClaim: calibre-web
        advancedMounts:
          calibre-web:
            app:
              - path: /config
      media:
        type: nfs
        server: nas.internal
        path: /volume1/media
        globalMounts:
          - path: /calibre-library
            subPath: books
          - path: /cwa-book-ingest
            subPath: downloads/openbooks
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
