---
groups:
  - name: cross-seed
    type: vlogs
    rules:
      - alert: CrossSeedDatabaseMalformed
        expr: |
          sum by (app) (count_over_time({app="cross-seed"} |~ "(?i)database disk image is malformed"[1h])) > 0
        for: 2m
        labels:
          severity: critical
          category: vlogs
        annotations:
          app: "{{ $labels.app }}"
          summary: "{{ $labels.app }} is experiencing database issues"
      - alert: CrossSeedFailedToInject
        expr: |
          sum by (app) (count_over_time({app="cross-seed"} |~ "(?i)failed to inject"[1h])) > 0
        for: 2m
        labels:
          severity: critical
          category: vlogs
        annotations:
          app: "{{ $labels.app }}"
          summary: "{{ $labels.app }} failed to inject a torrent"
