---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kube-prometheus-stack
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-stores
  interval: 30m
  path: ./kubernetes/apps/observability/kube-prometheus-stack/app
  postBuild:
    substitute:
      APP: kube-prometheus-stack
      GATUS_SUBDOMAIN: prometheus
  prune: false # revert to true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  targetNamespace: observability
  timeout: 5m
  wait: false
