---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: better-dcgm-dashboard
    files:
      # source: https://github.com/jfroy/flatops/blob/main/kubernetes/apps/gpu-operator/gpu-operator/app/resources/better-dcgm-dashboard.json
      - resources/better-dcgm-dashboard.json
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
      labels:
        grafana_dashboard: "1"
  - name: time-slicing-config-all
    files:
      - any=resources/time-slicing-config-all.yaml
generatorOptions:
  disableNameSuffixHash: true
