---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app radarr-uhd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      radarr:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: &secretName radarr-uhd-secret
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 5.23.0.9907@sha256:36cd279903d97e74fc687c937d6a5693a6fb69a01787203795b17ab66fb0e3e9
            env:
              RADARR__APP__INSTANCENAME: Radarr (UHD)
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
              RADARR__SERVER__PORT: &port 80
              RADARR__UPDATE__BRANCH: develop
              TZ: America/New_York
            envFrom: *envFrom
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi

          exporter:
            dependsOn: app
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.2.0
            args: ["radarr"]
            env:
              PORT: &metricsPort 9707
              URL: "http://{{ .Release.Name }}"
              ENABLE_ADDITIONAL_METRICS: "true"
              ENABLE_UNKNOWN_QUEUE_ITEMS: "true"
              API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *secretName
                    key: RADARR__AUTH__APIKEY
            probes:
              liveness: &metricsProbes
                <<: *probes
                spec:
                  httpGet:
                    path: /healthz
                    port: *metricsPort
              readiness: *metricsProbes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ "ALL" ] }

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [65568]
    service:
      app:
        controller: radarr
        nameOverride: *app
        ports:
          http:
            port: *port
          metrics:
            port: *metricsPort
    ingress:
      ts:
        className: tailscale
        hosts:
          - host: &tsHost "{{ .Release.Name }}.kite-harmonic.ts.net"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - *tsHost

    serviceMonitor:
      app:
        enabled: true
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 5m
            scrapeTimeout: 1m
            relabelings:
              - action: labeldrop
                regex: pod
              - action: replace
                replacement: *app
                targetLabel: instance

    persistence:
      config:
        type: emptyDir
      cache:
        existingClaim: radarr-uhd-cache
        globalMounts:
          - path: /config/MediaCover
            subPath: MediaCover
      scripts:
        type: configMap
        name: radarr-uhd-configmap
        defaultMode: 0775
        globalMounts:
          - path: /scripts/notify-pushover.sh
            subPath: notify-pushover.sh
            readOnly: true
      tmp:
        type: emptyDir
      media:
        type: nfs
        server: nas.internal
        path: /volume1/media
        globalMounts:
          - path: /media
