---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: radarr-uhd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr-uhd
      app.kubernetes.io/instance: radarr-uhd
  endpoints:
    - port: metrics
      path: /metrics
      interval: 5m
      scrapeTimeout: 1m
      relabelConfigs:
        - action: labeldrop
          regex: pod
        - action: replace
          targetLabel: instance
          replacement: radarr-uhd
