---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lidarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: lidarr-secret
    template:
      engineVersion: v2
      data:
        LIDARR__AUTH__APIKEY: "{{ .LIDARR_API_KEY }}"
        LIDARR__POSTGRES__HOST: redspot-rw.database.svc.cluster.local
        LIDARR__POSTGRES__PORT: "5432"
        LIDARR__POSTGRES__USER: "{{ .LIDARR_POSTGRES_USER }}"
        LIDARR__POSTGRES__PASSWORD: "{{ .LIDARR_POSTGRES_PASSWORD }}"
        LIDARR__POSTGRES__MAINDB: lidarr
        PUSHOVER_TOKEN: "{{ .LIDARR_PUSHOVER_TOKEN }}"
        PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: lidarr
