---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dawncraft
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      *app:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          *app:
            image:
              repository: ghcr.io/itzg/minecraft-server
              tag: 2025.10.5-java17
            env:
              EULA: "true"
              TZ: America/Chicago
              TYPE: "AUTO_CURSEFORGE"
              CF_SLUG: "dawn-craft"
              CF_FILENAME_MATCHER: "2.0.15"
              SERVER_NAME: *app
              DIFFICULTY: easy
              OPS: "zebernst,Snorlocke"
              ENABLE_ROLLING_LOGS: true
              ALLOW_FLIGHT: true
              INIT_MEMORY: 1G
              MAX_MEMORY: &max-memory 12G
              MODRINTH_PROJECTS: |
                bluemap
            envFrom:
              - secretRef:
                  name: dawncraft-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  exec: &probeexec { command: [ "mc-health" ] }
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 1
                  failureThreshold: 300
                  exec: *probeexec
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 2
                memory: *max-memory
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      modded:
        controller: *app
        annotations:
          mc-router.itzg.me/externalServerName: "dawncraft.zebernst.dev"
        ports:
          game:
           port: &game-port 25565
          rcon:
           port: &rcon-port 25578
          http:
            port: &web-port 8100
    route:
      modded:
        hostnames: ["dawncraft.zebernst.dev"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *web-port
            matches:
              - path:
                 type: PathPrefix
                 value: /
    persistence:
      tmp:
        type: emptyDir
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
