---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volsync
spec:
  selector:
    matchLabels:
      control-plane: volsync-controller
  endpoints:
    - port: https
      path: /metrics
      scheme: https
      interval: 1m
      scrapeTimeout: 10s
      tlsConfig:
        insecureSkipVerify: true
