---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: volsync
spec:
  selector:
    matchLabels:
      control-plane: volsync-controller
  endpoints:
    - port: https
      path: /metrics
      scheme: https
      interval: 1m
      scrapeTimeout: 10s
      tlsConfig:
        insecureSkipVerify: true
