---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: synology-csi-driver-credentials
    template:
      engineVersion: v2
      data:
        client-info.yml: |
          clients:
          - host: {{ .host }}
            port: {{ .port }}
            username: {{ .username }}
            password: {{ .password }}
            https: {{ .https }}
  dataFrom:
  - extract:
      key: synology-csi-credentials
