---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USERNAME }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_DBHOST: &dbHost redspot-rw.database.svc.cluster.local
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBUSER: &dbUser "{{ .PAPERLESS_POSTGRES_USER }}"
        PAPERLESS_DBPASS: &dbPass "{{ .PAPERLESS_POSTGRES_PASSWORD }}"
        PAPERLESS_DBNAME: &dbName paperless
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: paperless
      rewrite:
        - regexp:
            source: (.*)
            target: PAPERLESS_$1
    - extract:
        key: cloudnative-pg
