---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      # WEB-1080p
      # ref: https://trash-guides.info/Sonarr/sonarr-setup-quality-profiles/#web-1080p)
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      # Remux-1080p - Anime
      # ref: https://trash-guides.info/Sonarr/sonarr-setup-quality-profiles-anime/#quality-profile
      - template: sonarr-quality-definition-anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime
    quality_profiles:
      - name: WEB-1080p
      - name: Remux-1080p - Anime

radarr:
  radarr:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    quality_profiles:
      - name: SQP-1 (1080p)
      - name: Remux + WEB 1080p
    include:
      # SQP-1 (1080p)
      # ref: https://trash-guides.info/SQP/1/
      - template: radarr-quality-definition-sqp-streaming
      - template: radarr-quality-profile-sqp-1-1080p
      - template: radarr-custom-formats-sqp-1-1080p
      # Remux + WEB 1080p
      # ref: https://trash-guides.info/Radarr/radarr-setup-quality-profiles-french-en/#remux-web-1080p
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-remux-web-1080p
      - template: radarr-custom-formats-remux-web-1080p
