---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: choice
        default: "false"
        options: ["true", "false"]
      logLevel:
        description: Log Level
        type: choice
        default: info
        options: [debug, info, warn, error, fatal]
      version:
        description: Renovate version
        default: latest
        required: false
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches: ["main"]
    paths: [".github/renovate.json5", ".github/renovate/**.json5"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'info' }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  WORKFLOW_RENOVATE_VERSION: "${{ inputs.version || 'latest' }}"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@v41.0.21
        with:
          configurationFile: .github/renovate.json5
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"
