---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry Run
        type: choice
        default: "false"
        options:
          - "true"
          - "false"
      logLevel:
        description: Log Level
        type: choice
        default: debug
        options:
          - debug
          - info
          - warn
          - error
          - fatal
      version:
        description: Renovate version
        default: latest
        required: false
      repoCache:
        description: 'Reset or disable the cache?'
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
          - reset
  schedule:
  - cron: "0 * * * *" # Every hour
  push:
    branches: ["main"]
    paths:
    - .github/renovate.json5
    - .github/renovate/**.json5
  issues:
    types: ["edited"]
  issue_comment:
    types: ["edited"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: "${{ inputs.logLevel || 'debug' }}"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_DRY_RUN: "${{ inputs.dryRun == true }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  WORKFLOW_RENOVATE_VERSION: "${{ inputs.version || 'latest' }}"
  RENOVATE_REPOSITORY_CACHE: "${{ github.event.inputs.repoCache || 'enabled' }}"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Cache
        uses: actions/cache@v4
        if: github.event.inputs.repoCache != 'disabled'
        with:
          path: /tmp/renovate/cache/
          key: renovate-cache

      - name: Renovate
        uses: renovatebot/github-action@v40.3.3
        with:
          configurationFile: .github/renovate.json5
          token: "${{ steps.app-token.outputs.token }}"
          renovate-version: "${{ env.WORKFLOW_RENOVATE_VERSION }}"
          docker-user: 1001
