# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app agregarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system

  values:
    controllers:
      agregarr:
        containers:
          agregarr:
            image:
              repository: ghcr.io/agregarr/agregarr
              tag: v2.4.2
            env:
              PORT: &port 80
              TZ: America/Chicago
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    defaultPodOptions:
      priorityClassName: media-core
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      agregarr:
        controller: *app
        ports:
          http:
            port: *port

    route:
      internal:
        hostnames:
          - agregarr.zebernst.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /app/config
      tmpfs:
        type: emptyDir
        advancedMounts:
          agregarr:
            agregarr:
              - path: /app/config/logs
                subPath: logs
              - path: /tmp
                subPath: tmp
