# yaml-language-server: $schema=https://json.schemastore.org/kustomization
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external.yaml
  - hubble.yaml
  - lan.yaml
  - lan-l4-minecraft.yaml
  - lan-l4-plex.yaml
  - lan-l4-qbittorrent.yaml
  - lan-l4-steam.yaml
  - redirect.yaml
  - tailscale.yaml
  - tailscale-l4.yaml
