apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: tailscale-gateway-config
spec:
  service:
    type: LoadBalancer
    loadBalancerClass: tailscale
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tailscale
spec:
  gatewayClassName: cilium-ts
  infrastructure:
    parametersRef:
      group: cilium.io
      kind: CiliumGatewayClassConfig
      name: tailscale-gateway-config
    annotations:
      tailscale.com/hostname: cilium-gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.zebernst.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: zebernst-tls
            namespace: cert-manager
