apiVersion: cilium.io/v2alpha1
kind: CiliumGatewayClassConfig
metadata:
  name: tailscale-gateway-config
spec:
  service:
    type: LoadBalancer
    loadBalancerClass: tailscale
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-ts
spec:
  controllerName: io.cilium/gateway-controller
  description: Cilium GatewayClass backed by Tailscale LoadBalancer
  parametersRef:
    group: cilium.io
    kind: CiliumGatewayClassConfig
    name: tailscale-gateway-config
    namespace: kube-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tailscale
  annotations:
    external-dns.alpha.kubernetes.io/registry: unifi
spec:
  gatewayClassName: cilium-ts
  infrastructure:
    annotations:
      tailscale.com/hostname: cilium-gateway
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.zebernst.dev"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: zebernst-dev-tls
            namespace: cert-manager
