# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: holmesgpt-github-app
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: holmesgpt-github-app
  dataFrom:
    - extract:
        key: github-bot
